//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace TSN.ERP.SharedComponents.Data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsFilesInfo : DataSet {
        
        private GEN_FilesDataTable tableGEN_Files;
        
        public dsFilesInfo() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsFilesInfo(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["GEN_Files"] != null)) {
                    this.Tables.Add(new GEN_FilesDataTable(ds.Tables["GEN_Files"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GEN_FilesDataTable GEN_Files {
            get {
                return this.tableGEN_Files;
            }
        }
        
        public override DataSet Clone() {
            dsFilesInfo cln = ((dsFilesInfo)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["GEN_Files"] != null)) {
                this.Tables.Add(new GEN_FilesDataTable(ds.Tables["GEN_Files"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableGEN_Files = ((GEN_FilesDataTable)(this.Tables["GEN_Files"]));
            if ((this.tableGEN_Files != null)) {
                this.tableGEN_Files.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsFilesInfo";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsFilesInfo.xsd";
            this.Locale = new System.Globalization.CultureInfo("ar-EG");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableGEN_Files = new GEN_FilesDataTable();
            this.Tables.Add(this.tableGEN_Files);
        }
        
        private bool ShouldSerializeGEN_Files() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void GEN_FilesRowChangeEventHandler(object sender, GEN_FilesRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_FilesDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnFileID;
            
            private DataColumn columnUserID;
            
            private DataColumn columnFileName;
            
            private DataColumn columnFileSize;
            
            private DataColumn columnFileType;
            
            private DataColumn columnFileCreationTime;
            
            internal GEN_FilesDataTable() : 
                    base("GEN_Files") {
                this.InitClass();
            }
            
            internal GEN_FilesDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn FileIDColumn {
                get {
                    return this.columnFileID;
                }
            }
            
            internal DataColumn UserIDColumn {
                get {
                    return this.columnUserID;
                }
            }
            
            internal DataColumn FileNameColumn {
                get {
                    return this.columnFileName;
                }
            }
            
            internal DataColumn FileSizeColumn {
                get {
                    return this.columnFileSize;
                }
            }
            
            internal DataColumn FileTypeColumn {
                get {
                    return this.columnFileType;
                }
            }
            
            internal DataColumn FileCreationTimeColumn {
                get {
                    return this.columnFileCreationTime;
                }
            }
            
            public GEN_FilesRow this[int index] {
                get {
                    return ((GEN_FilesRow)(this.Rows[index]));
                }
            }
            
            public event GEN_FilesRowChangeEventHandler GEN_FilesRowChanged;
            
            public event GEN_FilesRowChangeEventHandler GEN_FilesRowChanging;
            
            public event GEN_FilesRowChangeEventHandler GEN_FilesRowDeleted;
            
            public event GEN_FilesRowChangeEventHandler GEN_FilesRowDeleting;
            
            public void AddGEN_FilesRow(GEN_FilesRow row) {
                this.Rows.Add(row);
            }
            
            public GEN_FilesRow AddGEN_FilesRow(int FileID, int UserID, string FileName, string FileSize, string FileType, System.DateTime FileCreationTime) {
                GEN_FilesRow rowGEN_FilesRow = ((GEN_FilesRow)(this.NewRow()));
                rowGEN_FilesRow.ItemArray = new object[] {
                        FileID,
                        UserID,
                        FileName,
                        FileSize,
                        FileType,
                        FileCreationTime};
                this.Rows.Add(rowGEN_FilesRow);
                return rowGEN_FilesRow;
            }
            
            public GEN_FilesRow FindByFileID(int FileID) {
                return ((GEN_FilesRow)(this.Rows.Find(new object[] {
                            FileID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                GEN_FilesDataTable cln = ((GEN_FilesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new GEN_FilesDataTable();
            }
            
            internal void InitVars() {
                this.columnFileID = this.Columns["FileID"];
                this.columnUserID = this.Columns["UserID"];
                this.columnFileName = this.Columns["FileName"];
                this.columnFileSize = this.Columns["FileSize"];
                this.columnFileType = this.Columns["FileType"];
                this.columnFileCreationTime = this.Columns["FileCreationTime"];
            }
            
            private void InitClass() {
                this.columnFileID = new DataColumn("FileID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFileID);
                this.columnUserID = new DataColumn("UserID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserID);
                this.columnFileName = new DataColumn("FileName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFileName);
                this.columnFileSize = new DataColumn("FileSize", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFileSize);
                this.columnFileType = new DataColumn("FileType", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFileType);
                this.columnFileCreationTime = new DataColumn("FileCreationTime", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFileCreationTime);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnFileID}, true));
                this.columnFileID.AllowDBNull = false;
                this.columnFileID.Unique = true;
                this.columnFileName.AllowDBNull = false;
                this.columnFileSize.AllowDBNull = false;
                this.columnFileType.AllowDBNull = false;
                this.columnFileCreationTime.AllowDBNull = false;
            }
            
            public GEN_FilesRow NewGEN_FilesRow() {
                return ((GEN_FilesRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new GEN_FilesRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(GEN_FilesRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GEN_FilesRowChanged != null)) {
                    this.GEN_FilesRowChanged(this, new GEN_FilesRowChangeEvent(((GEN_FilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GEN_FilesRowChanging != null)) {
                    this.GEN_FilesRowChanging(this, new GEN_FilesRowChangeEvent(((GEN_FilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GEN_FilesRowDeleted != null)) {
                    this.GEN_FilesRowDeleted(this, new GEN_FilesRowChangeEvent(((GEN_FilesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GEN_FilesRowDeleting != null)) {
                    this.GEN_FilesRowDeleting(this, new GEN_FilesRowChangeEvent(((GEN_FilesRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveGEN_FilesRow(GEN_FilesRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_FilesRow : DataRow {
            
            private GEN_FilesDataTable tableGEN_Files;
            
            internal GEN_FilesRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableGEN_Files = ((GEN_FilesDataTable)(this.Table));
            }
            
            public int FileID {
                get {
                    return ((int)(this[this.tableGEN_Files.FileIDColumn]));
                }
                set {
                    this[this.tableGEN_Files.FileIDColumn] = value;
                }
            }
            
            public int UserID {
                get {
                    try {
                        return ((int)(this[this.tableGEN_Files.UserIDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_Files.UserIDColumn] = value;
                }
            }
            
            public string FileName {
                get {
                    return ((string)(this[this.tableGEN_Files.FileNameColumn]));
                }
                set {
                    this[this.tableGEN_Files.FileNameColumn] = value;
                }
            }
            
            public string FileSize {
                get {
                    return ((string)(this[this.tableGEN_Files.FileSizeColumn]));
                }
                set {
                    this[this.tableGEN_Files.FileSizeColumn] = value;
                }
            }
            
            public string FileType {
                get {
                    return ((string)(this[this.tableGEN_Files.FileTypeColumn]));
                }
                set {
                    this[this.tableGEN_Files.FileTypeColumn] = value;
                }
            }
            
            public System.DateTime FileCreationTime {
                get {
                    return ((System.DateTime)(this[this.tableGEN_Files.FileCreationTimeColumn]));
                }
                set {
                    this[this.tableGEN_Files.FileCreationTimeColumn] = value;
                }
            }
            
            public bool IsUserIDNull() {
                return this.IsNull(this.tableGEN_Files.UserIDColumn);
            }
            
            public void SetUserIDNull() {
                this[this.tableGEN_Files.UserIDColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_FilesRowChangeEvent : EventArgs {
            
            private GEN_FilesRow eventRow;
            
            private DataRowAction eventAction;
            
            public GEN_FilesRowChangeEvent(GEN_FilesRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public GEN_FilesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
