//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace TSN.ERP.SharedComponents.Data {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsMFGMemberTasks : DataSet {
        
        private GEN_MFGMemberTasksDataTable tableGEN_MFGMemberTasks;
        
        public dsMFGMemberTasks() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsMFGMemberTasks(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["GEN_MFGMemberTasks"] != null)) {
                    this.Tables.Add(new GEN_MFGMemberTasksDataTable(ds.Tables["GEN_MFGMemberTasks"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GEN_MFGMemberTasksDataTable GEN_MFGMemberTasks {
            get {
                return this.tableGEN_MFGMemberTasks;
            }
        }
        
        public override DataSet Clone() {
            dsMFGMemberTasks cln = ((dsMFGMemberTasks)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["GEN_MFGMemberTasks"] != null)) {
                this.Tables.Add(new GEN_MFGMemberTasksDataTable(ds.Tables["GEN_MFGMemberTasks"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableGEN_MFGMemberTasks = ((GEN_MFGMemberTasksDataTable)(this.Tables["GEN_MFGMemberTasks"]));
            if ((this.tableGEN_MFGMemberTasks != null)) {
                this.tableGEN_MFGMemberTasks.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsMFGMemberTasks";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/dsMFGMemberTasks.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableGEN_MFGMemberTasks = new GEN_MFGMemberTasksDataTable();
            this.Tables.Add(this.tableGEN_MFGMemberTasks);
        }
        
        private bool ShouldSerializeGEN_MFGMemberTasks() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void GEN_MFGMemberTasksRowChangeEventHandler(object sender, GEN_MFGMemberTasksRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_MFGMemberTasksDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnTrvID;
            
            private DataColumn columnTrvNumber;
            
            private DataColumn columnCompnay;
            
            private DataColumn columnClipMember;
            
            private DataColumn columnPartClass;
            
            private DataColumn columnPartNumber;
            
            private DataColumn columnOperation;
            
            private DataColumn columnQuantity;
            
            private DataColumn columnHours;
            
            private DataColumn columnContactID;
            
            private DataColumn columnTaskDate;
            
            private DataColumn columnEnteredBy;
            
            internal GEN_MFGMemberTasksDataTable() : 
                    base("GEN_MFGMemberTasks") {
                this.InitClass();
            }
            
            internal GEN_MFGMemberTasksDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn TrvIDColumn {
                get {
                    return this.columnTrvID;
                }
            }
            
            internal DataColumn TrvNumberColumn {
                get {
                    return this.columnTrvNumber;
                }
            }
            
            internal DataColumn CompnayColumn {
                get {
                    return this.columnCompnay;
                }
            }
            
            internal DataColumn ClipMemberColumn {
                get {
                    return this.columnClipMember;
                }
            }
            
            internal DataColumn PartClassColumn {
                get {
                    return this.columnPartClass;
                }
            }
            
            internal DataColumn PartNumberColumn {
                get {
                    return this.columnPartNumber;
                }
            }
            
            internal DataColumn OperationColumn {
                get {
                    return this.columnOperation;
                }
            }
            
            internal DataColumn QuantityColumn {
                get {
                    return this.columnQuantity;
                }
            }
            
            internal DataColumn HoursColumn {
                get {
                    return this.columnHours;
                }
            }
            
            internal DataColumn ContactIDColumn {
                get {
                    return this.columnContactID;
                }
            }
            
            internal DataColumn TaskDateColumn {
                get {
                    return this.columnTaskDate;
                }
            }
            
            internal DataColumn EnteredByColumn {
                get {
                    return this.columnEnteredBy;
                }
            }
            
            public GEN_MFGMemberTasksRow this[int index] {
                get {
                    return ((GEN_MFGMemberTasksRow)(this.Rows[index]));
                }
            }
            
            public event GEN_MFGMemberTasksRowChangeEventHandler GEN_MFGMemberTasksRowChanged;
            
            public event GEN_MFGMemberTasksRowChangeEventHandler GEN_MFGMemberTasksRowChanging;
            
            public event GEN_MFGMemberTasksRowChangeEventHandler GEN_MFGMemberTasksRowDeleted;
            
            public event GEN_MFGMemberTasksRowChangeEventHandler GEN_MFGMemberTasksRowDeleting;
            
            public void AddGEN_MFGMemberTasksRow(GEN_MFGMemberTasksRow row) {
                this.Rows.Add(row);
            }
            
            public GEN_MFGMemberTasksRow AddGEN_MFGMemberTasksRow(int TrvID, long TrvNumber, string Compnay, string ClipMember, string PartClass, string PartNumber, string Operation, int Quantity, System.Double Hours, int ContactID, System.DateTime TaskDate, int EnteredBy) {
                GEN_MFGMemberTasksRow rowGEN_MFGMemberTasksRow = ((GEN_MFGMemberTasksRow)(this.NewRow()));
                rowGEN_MFGMemberTasksRow.ItemArray = new object[] {
                        TrvID,
                        TrvNumber,
                        Compnay,
                        ClipMember,
                        PartClass,
                        PartNumber,
                        Operation,
                        Quantity,
                        Hours,
                        ContactID,
                        TaskDate,
                        EnteredBy};
                this.Rows.Add(rowGEN_MFGMemberTasksRow);
                return rowGEN_MFGMemberTasksRow;
            }
            
            public GEN_MFGMemberTasksRow FindByTrvID(int TrvID) {
                return ((GEN_MFGMemberTasksRow)(this.Rows.Find(new object[] {
                            TrvID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                GEN_MFGMemberTasksDataTable cln = ((GEN_MFGMemberTasksDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new GEN_MFGMemberTasksDataTable();
            }
            
            internal void InitVars() {
                this.columnTrvID = this.Columns["TrvID"];
                this.columnTrvNumber = this.Columns["TrvNumber"];
                this.columnCompnay = this.Columns["Compnay"];
                this.columnClipMember = this.Columns["ClipMember"];
                this.columnPartClass = this.Columns["PartClass"];
                this.columnPartNumber = this.Columns["PartNumber"];
                this.columnOperation = this.Columns["Operation"];
                this.columnQuantity = this.Columns["Quantity"];
                this.columnHours = this.Columns["Hours"];
                this.columnContactID = this.Columns["ContactID"];
                this.columnTaskDate = this.Columns["TaskDate"];
                this.columnEnteredBy = this.Columns["EnteredBy"];
            }
            
            private void InitClass() {
                this.columnTrvID = new DataColumn("TrvID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTrvID);
                this.columnTrvNumber = new DataColumn("TrvNumber", typeof(long), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTrvNumber);
                this.columnCompnay = new DataColumn("Compnay", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCompnay);
                this.columnClipMember = new DataColumn("ClipMember", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnClipMember);
                this.columnPartClass = new DataColumn("PartClass", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPartClass);
                this.columnPartNumber = new DataColumn("PartNumber", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPartNumber);
                this.columnOperation = new DataColumn("Operation", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnOperation);
                this.columnQuantity = new DataColumn("Quantity", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQuantity);
                this.columnHours = new DataColumn("Hours", typeof(System.Double), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHours);
                this.columnContactID = new DataColumn("ContactID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnContactID);
                this.columnTaskDate = new DataColumn("TaskDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTaskDate);
                this.columnEnteredBy = new DataColumn("EnteredBy", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEnteredBy);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnTrvID}, true));
                this.columnTrvID.AllowDBNull = false;
                this.columnTrvID.Unique = true;
                this.columnTrvNumber.AllowDBNull = false;
                this.columnQuantity.AllowDBNull = false;
                this.columnHours.AllowDBNull = false;
                this.columnContactID.AllowDBNull = false;
                this.columnTaskDate.AllowDBNull = false;
                this.columnEnteredBy.AllowDBNull = false;
            }
            
            public GEN_MFGMemberTasksRow NewGEN_MFGMemberTasksRow() {
                return ((GEN_MFGMemberTasksRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new GEN_MFGMemberTasksRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(GEN_MFGMemberTasksRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GEN_MFGMemberTasksRowChanged != null)) {
                    this.GEN_MFGMemberTasksRowChanged(this, new GEN_MFGMemberTasksRowChangeEvent(((GEN_MFGMemberTasksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GEN_MFGMemberTasksRowChanging != null)) {
                    this.GEN_MFGMemberTasksRowChanging(this, new GEN_MFGMemberTasksRowChangeEvent(((GEN_MFGMemberTasksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GEN_MFGMemberTasksRowDeleted != null)) {
                    this.GEN_MFGMemberTasksRowDeleted(this, new GEN_MFGMemberTasksRowChangeEvent(((GEN_MFGMemberTasksRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GEN_MFGMemberTasksRowDeleting != null)) {
                    this.GEN_MFGMemberTasksRowDeleting(this, new GEN_MFGMemberTasksRowChangeEvent(((GEN_MFGMemberTasksRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveGEN_MFGMemberTasksRow(GEN_MFGMemberTasksRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_MFGMemberTasksRow : DataRow {
            
            private GEN_MFGMemberTasksDataTable tableGEN_MFGMemberTasks;
            
            internal GEN_MFGMemberTasksRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableGEN_MFGMemberTasks = ((GEN_MFGMemberTasksDataTable)(this.Table));
            }
            
            public int TrvID {
                get {
                    return ((int)(this[this.tableGEN_MFGMemberTasks.TrvIDColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.TrvIDColumn] = value;
                }
            }
            
            public long TrvNumber {
                get {
                    return ((long)(this[this.tableGEN_MFGMemberTasks.TrvNumberColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.TrvNumberColumn] = value;
                }
            }
            
            public string Compnay {
                get {
                    try {
                        return ((string)(this[this.tableGEN_MFGMemberTasks.CompnayColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.CompnayColumn] = value;
                }
            }
            
            public string ClipMember {
                get {
                    try {
                        return ((string)(this[this.tableGEN_MFGMemberTasks.ClipMemberColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.ClipMemberColumn] = value;
                }
            }
            
            public string PartClass {
                get {
                    try {
                        return ((string)(this[this.tableGEN_MFGMemberTasks.PartClassColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.PartClassColumn] = value;
                }
            }
            
            public string PartNumber {
                get {
                    try {
                        return ((string)(this[this.tableGEN_MFGMemberTasks.PartNumberColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.PartNumberColumn] = value;
                }
            }
            
            public string Operation {
                get {
                    try {
                        return ((string)(this[this.tableGEN_MFGMemberTasks.OperationColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.OperationColumn] = value;
                }
            }
            
            public int Quantity {
                get {
                    return ((int)(this[this.tableGEN_MFGMemberTasks.QuantityColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.QuantityColumn] = value;
                }
            }
            
            public System.Double Hours {
                get {
                    return ((System.Double)(this[this.tableGEN_MFGMemberTasks.HoursColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.HoursColumn] = value;
                }
            }
            
            public int ContactID {
                get {
                    return ((int)(this[this.tableGEN_MFGMemberTasks.ContactIDColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.ContactIDColumn] = value;
                }
            }
            
            public System.DateTime TaskDate {
                get {
                    return ((System.DateTime)(this[this.tableGEN_MFGMemberTasks.TaskDateColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.TaskDateColumn] = value;
                }
            }
            
            public int EnteredBy {
                get {
                    return ((int)(this[this.tableGEN_MFGMemberTasks.EnteredByColumn]));
                }
                set {
                    this[this.tableGEN_MFGMemberTasks.EnteredByColumn] = value;
                }
            }
            
            public bool IsCompnayNull() {
                return this.IsNull(this.tableGEN_MFGMemberTasks.CompnayColumn);
            }
            
            public void SetCompnayNull() {
                this[this.tableGEN_MFGMemberTasks.CompnayColumn] = System.Convert.DBNull;
            }
            
            public bool IsClipMemberNull() {
                return this.IsNull(this.tableGEN_MFGMemberTasks.ClipMemberColumn);
            }
            
            public void SetClipMemberNull() {
                this[this.tableGEN_MFGMemberTasks.ClipMemberColumn] = System.Convert.DBNull;
            }
            
            public bool IsPartClassNull() {
                return this.IsNull(this.tableGEN_MFGMemberTasks.PartClassColumn);
            }
            
            public void SetPartClassNull() {
                this[this.tableGEN_MFGMemberTasks.PartClassColumn] = System.Convert.DBNull;
            }
            
            public bool IsPartNumberNull() {
                return this.IsNull(this.tableGEN_MFGMemberTasks.PartNumberColumn);
            }
            
            public void SetPartNumberNull() {
                this[this.tableGEN_MFGMemberTasks.PartNumberColumn] = System.Convert.DBNull;
            }
            
            public bool IsOperationNull() {
                return this.IsNull(this.tableGEN_MFGMemberTasks.OperationColumn);
            }
            
            public void SetOperationNull() {
                this[this.tableGEN_MFGMemberTasks.OperationColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class GEN_MFGMemberTasksRowChangeEvent : EventArgs {
            
            private GEN_MFGMemberTasksRow eventRow;
            
            private DataRowAction eventAction;
            
            public GEN_MFGMemberTasksRowChangeEvent(GEN_MFGMemberTasksRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public GEN_MFGMemberTasksRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
