//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace TSN.ERP.GUIManagement.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DsFunctionalities")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DsFunctionalities : System.Data.DataSet {
        
        private GUI_FunctionalitiesDataTable tableGUI_Functionalities;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DsFunctionalities() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DsFunctionalities(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["GUI_Functionalities"] != null)) {
                    base.Tables.Add(new GUI_FunctionalitiesDataTable(ds.Tables["GUI_Functionalities"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public GUI_FunctionalitiesDataTable GUI_Functionalities {
            get {
                return this.tableGUI_Functionalities;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DsFunctionalities cln = ((DsFunctionalities)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["GUI_Functionalities"] != null)) {
                    base.Tables.Add(new GUI_FunctionalitiesDataTable(ds.Tables["GUI_Functionalities"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableGUI_Functionalities = ((GUI_FunctionalitiesDataTable)(base.Tables["GUI_Functionalities"]));
            if ((initTable == true)) {
                if ((this.tableGUI_Functionalities != null)) {
                    this.tableGUI_Functionalities.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DsFunctionalities";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DsFunctionalities.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableGUI_Functionalities = new GUI_FunctionalitiesDataTable();
            base.Tables.Add(this.tableGUI_Functionalities);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeGUI_Functionalities() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DsFunctionalities ds = new DsFunctionalities();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void GUI_FunctionalitiesRowChangeEventHandler(object sender, GUI_FunctionalitiesRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class GUI_FunctionalitiesDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnGFunID;
            
            private System.Data.DataColumn columnLinkID;
            
            private System.Data.DataColumn columnGFunName;
            
            private System.Data.DataColumn columnGFunUserControl;
            
            private System.Data.DataColumn columnGFunVisible;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesDataTable() {
                this.TableName = "GUI_Functionalities";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal GUI_FunctionalitiesDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected GUI_FunctionalitiesDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn GFunIDColumn {
                get {
                    return this.columnGFunID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn LinkIDColumn {
                get {
                    return this.columnLinkID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn GFunNameColumn {
                get {
                    return this.columnGFunName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn GFunUserControlColumn {
                get {
                    return this.columnGFunUserControl;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn GFunVisibleColumn {
                get {
                    return this.columnGFunVisible;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRow this[int index] {
                get {
                    return ((GUI_FunctionalitiesRow)(this.Rows[index]));
                }
            }
            
            public event GUI_FunctionalitiesRowChangeEventHandler GUI_FunctionalitiesRowChanging;
            
            public event GUI_FunctionalitiesRowChangeEventHandler GUI_FunctionalitiesRowChanged;
            
            public event GUI_FunctionalitiesRowChangeEventHandler GUI_FunctionalitiesRowDeleting;
            
            public event GUI_FunctionalitiesRowChangeEventHandler GUI_FunctionalitiesRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddGUI_FunctionalitiesRow(GUI_FunctionalitiesRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRow AddGUI_FunctionalitiesRow(int GFunID, int LinkID, string GFunName, string GFunUserControl, bool GFunVisible) {
                GUI_FunctionalitiesRow rowGUI_FunctionalitiesRow = ((GUI_FunctionalitiesRow)(this.NewRow()));
                rowGUI_FunctionalitiesRow.ItemArray = new object[] {
                        GFunID,
                        LinkID,
                        GFunName,
                        GFunUserControl,
                        GFunVisible};
                this.Rows.Add(rowGUI_FunctionalitiesRow);
                return rowGUI_FunctionalitiesRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRow FindByGFunID(int GFunID) {
                return ((GUI_FunctionalitiesRow)(this.Rows.Find(new object[] {
                            GFunID})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                GUI_FunctionalitiesDataTable cln = ((GUI_FunctionalitiesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new GUI_FunctionalitiesDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnGFunID = base.Columns["GFunID"];
                this.columnLinkID = base.Columns["LinkID"];
                this.columnGFunName = base.Columns["GFunName"];
                this.columnGFunUserControl = base.Columns["GFunUserControl"];
                this.columnGFunVisible = base.Columns["GFunVisible"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnGFunID = new System.Data.DataColumn("GFunID", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnGFunID);
                this.columnLinkID = new System.Data.DataColumn("LinkID", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnLinkID);
                this.columnGFunName = new System.Data.DataColumn("GFunName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnGFunName);
                this.columnGFunUserControl = new System.Data.DataColumn("GFunUserControl", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnGFunUserControl);
                this.columnGFunVisible = new System.Data.DataColumn("GFunVisible", typeof(bool), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnGFunVisible);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnGFunID}, true));
                this.columnGFunID.AllowDBNull = false;
                this.columnGFunID.Unique = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRow NewGUI_FunctionalitiesRow() {
                return ((GUI_FunctionalitiesRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new GUI_FunctionalitiesRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(GUI_FunctionalitiesRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.GUI_FunctionalitiesRowChanged != null)) {
                    this.GUI_FunctionalitiesRowChanged(this, new GUI_FunctionalitiesRowChangeEvent(((GUI_FunctionalitiesRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.GUI_FunctionalitiesRowChanging != null)) {
                    this.GUI_FunctionalitiesRowChanging(this, new GUI_FunctionalitiesRowChangeEvent(((GUI_FunctionalitiesRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.GUI_FunctionalitiesRowDeleted != null)) {
                    this.GUI_FunctionalitiesRowDeleted(this, new GUI_FunctionalitiesRowChangeEvent(((GUI_FunctionalitiesRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.GUI_FunctionalitiesRowDeleting != null)) {
                    this.GUI_FunctionalitiesRowDeleting(this, new GUI_FunctionalitiesRowChangeEvent(((GUI_FunctionalitiesRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveGUI_FunctionalitiesRow(GUI_FunctionalitiesRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DsFunctionalities ds = new DsFunctionalities();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "GUI_FunctionalitiesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class GUI_FunctionalitiesRow : System.Data.DataRow {
            
            private GUI_FunctionalitiesDataTable tableGUI_Functionalities;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal GUI_FunctionalitiesRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableGUI_Functionalities = ((GUI_FunctionalitiesDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int GFunID {
                get {
                    return ((int)(this[this.tableGUI_Functionalities.GFunIDColumn]));
                }
                set {
                    this[this.tableGUI_Functionalities.GFunIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int LinkID {
                get {
                    try {
                        return ((int)(this[this.tableGUI_Functionalities.LinkIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'LinkID\' in table \'GUI_Functionalities\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_Functionalities.LinkIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GFunName {
                get {
                    try {
                        return ((string)(this[this.tableGUI_Functionalities.GFunNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'GFunName\' in table \'GUI_Functionalities\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_Functionalities.GFunNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GFunUserControl {
                get {
                    try {
                        return ((string)(this[this.tableGUI_Functionalities.GFunUserControlColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'GFunUserControl\' in table \'GUI_Functionalities\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_Functionalities.GFunUserControlColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool GFunVisible {
                get {
                    try {
                        return ((bool)(this[this.tableGUI_Functionalities.GFunVisibleColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'GFunVisible\' in table \'GUI_Functionalities\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableGUI_Functionalities.GFunVisibleColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLinkIDNull() {
                return this.IsNull(this.tableGUI_Functionalities.LinkIDColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLinkIDNull() {
                this[this.tableGUI_Functionalities.LinkIDColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGFunNameNull() {
                return this.IsNull(this.tableGUI_Functionalities.GFunNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGFunNameNull() {
                this[this.tableGUI_Functionalities.GFunNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGFunUserControlNull() {
                return this.IsNull(this.tableGUI_Functionalities.GFunUserControlColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGFunUserControlNull() {
                this[this.tableGUI_Functionalities.GFunUserControlColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGFunVisibleNull() {
                return this.IsNull(this.tableGUI_Functionalities.GFunVisibleColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGFunVisibleNull() {
                this[this.tableGUI_Functionalities.GFunVisibleColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class GUI_FunctionalitiesRowChangeEvent : System.EventArgs {
            
            private GUI_FunctionalitiesRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRowChangeEvent(GUI_FunctionalitiesRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public GUI_FunctionalitiesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591