//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace TSN.ERP.Security.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DataSetAllUGForRG")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSetAllUGForRG : System.Data.DataSet {
        
        private SEC_UsersGroupsXRulesGroupsDataTable tableSEC_UsersGroupsXRulesGroups;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DataSetAllUGForRG() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DataSetAllUGForRG(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["SEC_UsersGroupsXRulesGroups"] != null)) {
                    base.Tables.Add(new SEC_UsersGroupsXRulesGroupsDataTable(ds.Tables["SEC_UsersGroupsXRulesGroups"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SEC_UsersGroupsXRulesGroupsDataTable SEC_UsersGroupsXRulesGroups {
            get {
                return this.tableSEC_UsersGroupsXRulesGroups;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DataSetAllUGForRG cln = ((DataSetAllUGForRG)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["SEC_UsersGroupsXRulesGroups"] != null)) {
                    base.Tables.Add(new SEC_UsersGroupsXRulesGroupsDataTable(ds.Tables["SEC_UsersGroupsXRulesGroups"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableSEC_UsersGroupsXRulesGroups = ((SEC_UsersGroupsXRulesGroupsDataTable)(base.Tables["SEC_UsersGroupsXRulesGroups"]));
            if ((initTable == true)) {
                if ((this.tableSEC_UsersGroupsXRulesGroups != null)) {
                    this.tableSEC_UsersGroupsXRulesGroups.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DataSetAllUGForRG";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSetAllUGForRG.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableSEC_UsersGroupsXRulesGroups = new SEC_UsersGroupsXRulesGroupsDataTable();
            base.Tables.Add(this.tableSEC_UsersGroupsXRulesGroups);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeSEC_UsersGroupsXRulesGroups() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DataSetAllUGForRG ds = new DataSetAllUGForRG();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void SEC_UsersGroupsXRulesGroupsRowChangeEventHandler(object sender, SEC_UsersGroupsXRulesGroupsRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SEC_UsersGroupsXRulesGroupsDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnUserGroupID;
            
            private System.Data.DataColumn columnRuleGroupID;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsDataTable() {
                this.TableName = "SEC_UsersGroupsXRulesGroups";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SEC_UsersGroupsXRulesGroupsDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected SEC_UsersGroupsXRulesGroupsDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn UserGroupIDColumn {
                get {
                    return this.columnUserGroupID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn RuleGroupIDColumn {
                get {
                    return this.columnRuleGroupID;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRow this[int index] {
                get {
                    return ((SEC_UsersGroupsXRulesGroupsRow)(this.Rows[index]));
                }
            }
            
            public event SEC_UsersGroupsXRulesGroupsRowChangeEventHandler SEC_UsersGroupsXRulesGroupsRowChanging;
            
            public event SEC_UsersGroupsXRulesGroupsRowChangeEventHandler SEC_UsersGroupsXRulesGroupsRowChanged;
            
            public event SEC_UsersGroupsXRulesGroupsRowChangeEventHandler SEC_UsersGroupsXRulesGroupsRowDeleting;
            
            public event SEC_UsersGroupsXRulesGroupsRowChangeEventHandler SEC_UsersGroupsXRulesGroupsRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddSEC_UsersGroupsXRulesGroupsRow(SEC_UsersGroupsXRulesGroupsRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRow AddSEC_UsersGroupsXRulesGroupsRow(int UserGroupID, int RuleGroupID) {
                SEC_UsersGroupsXRulesGroupsRow rowSEC_UsersGroupsXRulesGroupsRow = ((SEC_UsersGroupsXRulesGroupsRow)(this.NewRow()));
                rowSEC_UsersGroupsXRulesGroupsRow.ItemArray = new object[] {
                        UserGroupID,
                        RuleGroupID};
                this.Rows.Add(rowSEC_UsersGroupsXRulesGroupsRow);
                return rowSEC_UsersGroupsXRulesGroupsRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRow FindByUserGroupIDRuleGroupID(int UserGroupID, int RuleGroupID) {
                return ((SEC_UsersGroupsXRulesGroupsRow)(this.Rows.Find(new object[] {
                            UserGroupID,
                            RuleGroupID})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                SEC_UsersGroupsXRulesGroupsDataTable cln = ((SEC_UsersGroupsXRulesGroupsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new SEC_UsersGroupsXRulesGroupsDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnUserGroupID = base.Columns["UserGroupID"];
                this.columnRuleGroupID = base.Columns["RuleGroupID"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnUserGroupID = new System.Data.DataColumn("UserGroupID", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnUserGroupID);
                this.columnRuleGroupID = new System.Data.DataColumn("RuleGroupID", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRuleGroupID);
                this.Constraints.Add(new System.Data.UniqueConstraint("Constraint1", new System.Data.DataColumn[] {
                                this.columnUserGroupID,
                                this.columnRuleGroupID}, true));
                this.columnUserGroupID.AllowDBNull = false;
                this.columnRuleGroupID.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRow NewSEC_UsersGroupsXRulesGroupsRow() {
                return ((SEC_UsersGroupsXRulesGroupsRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new SEC_UsersGroupsXRulesGroupsRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(SEC_UsersGroupsXRulesGroupsRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SEC_UsersGroupsXRulesGroupsRowChanged != null)) {
                    this.SEC_UsersGroupsXRulesGroupsRowChanged(this, new SEC_UsersGroupsXRulesGroupsRowChangeEvent(((SEC_UsersGroupsXRulesGroupsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SEC_UsersGroupsXRulesGroupsRowChanging != null)) {
                    this.SEC_UsersGroupsXRulesGroupsRowChanging(this, new SEC_UsersGroupsXRulesGroupsRowChangeEvent(((SEC_UsersGroupsXRulesGroupsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SEC_UsersGroupsXRulesGroupsRowDeleted != null)) {
                    this.SEC_UsersGroupsXRulesGroupsRowDeleted(this, new SEC_UsersGroupsXRulesGroupsRowChangeEvent(((SEC_UsersGroupsXRulesGroupsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SEC_UsersGroupsXRulesGroupsRowDeleting != null)) {
                    this.SEC_UsersGroupsXRulesGroupsRowDeleting(this, new SEC_UsersGroupsXRulesGroupsRowChangeEvent(((SEC_UsersGroupsXRulesGroupsRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveSEC_UsersGroupsXRulesGroupsRow(SEC_UsersGroupsXRulesGroupsRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DataSetAllUGForRG ds = new DataSetAllUGForRG();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SEC_UsersGroupsXRulesGroupsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class SEC_UsersGroupsXRulesGroupsRow : System.Data.DataRow {
            
            private SEC_UsersGroupsXRulesGroupsDataTable tableSEC_UsersGroupsXRulesGroups;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal SEC_UsersGroupsXRulesGroupsRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableSEC_UsersGroupsXRulesGroups = ((SEC_UsersGroupsXRulesGroupsDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int UserGroupID {
                get {
                    return ((int)(this[this.tableSEC_UsersGroupsXRulesGroups.UserGroupIDColumn]));
                }
                set {
                    this[this.tableSEC_UsersGroupsXRulesGroups.UserGroupIDColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int RuleGroupID {
                get {
                    return ((int)(this[this.tableSEC_UsersGroupsXRulesGroups.RuleGroupIDColumn]));
                }
                set {
                    this[this.tableSEC_UsersGroupsXRulesGroups.RuleGroupIDColumn] = value;
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class SEC_UsersGroupsXRulesGroupsRowChangeEvent : System.EventArgs {
            
            private SEC_UsersGroupsXRulesGroupsRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRowChangeEvent(SEC_UsersGroupsXRulesGroupsRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public SEC_UsersGroupsXRulesGroupsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591